### ISSUE TITLE
Module name?

### ISSUE THREAD

**Issue by assistcontrol** [perlancar/perl-PERLANCAR-Exporter-Lite#1]
Putting this module in an obscure namespace (sorry, but naming it after yourself _is_ obscure) makes it come across like this module only exists to prove a point to NEILB.

This module seems like a great idea, and the numbers from `Bencher::Scenario::Exporters::Startup` are impressive. So, how about making it clear that this module is for people to use, not just yourself? And if the module isn't for other people to use, the documentation should say so.

`Exporter::Tiniest`, `Exporter::Litest`, `Exporte ("so light, it only needs 1 'r'")`, `Exporter::Simplest`, `Exporter::Smallest`, `Ex::Porter (could be beer themed)`, `Ex::Porterhouse (could be steak themed)`... there are many good possibilities. It deserves to have a proper name.

**Comment by perlancar** [comment]
Thanks for the comment. I have a few other modules under PERLANCAR::\* aside from this. They are there because they are experimental. Usually I'm the only one using them. Eventually some of them will be renamed to more proper names, if they are useful and matter enough. Time and feedback will tell.

**Comment by assistcontrol** [comment]
A super-fast and properly lightweight Exporter, that does only what it advertises, is most definitely useful and matters!

**Comment by perlancar** [comment]
There is no particular trick I'm using which is special though. Especially, compared to Exporter::Lite, the main difference is that I avoid loading `warnings` (and to a lesser extent `strict`). Relatively speaking, `warnings` is heavy in this case. Also, I still need to make sure there are no bugs, especially after I completely botched 0.01 :p

**Comment by perlancar** [comment]
I'm closing this issue for now. Name might be changed if there are enough demand, which is not the case ATM.
